version: "3.9"
services:
  backend:
    build: ./backend
    env_file: .env
    restart: unless-stopped

  frontend:
    build: ./frontend
    env_file: .env
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
